import type { Metadata } from "next";
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import "./globals.css";
import Shell from "@/components/AppShell";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <ColorSchemeScript />
      </head>
      <body className="bg-white">
        <MantineProvider>
          <Shell>{children}</Shell>
        
        </MantineProvider>
      </body>
    </html>
  );
}
